import { JSDOM } from "jsdom";
import { findElementsWithMatcher, findNextSiblingWithContent } from "./utils";

/** Extracts the link URL from Google Docs links
 *
 * Links from the HTML generated by google docs use the format `https://google.com/url?q=<your link>&...`
 *
 * The link you actually want is in the `q` query parameter
 *
 * If `docsHref` does not exist or is not a valid URL, this will return the input value unchanged.
 *
 * @param {string} docsHref The URL from the Google Doc Link href
 * @returns {string}
 */
export const extractLinkUrl = (docsHref = ""): string => {
    try {
        const urlObj = new URL(docsHref);
        const redirectUrl = urlObj.searchParams.get("q");
        return redirectUrl ?? docsHref;
    } catch (err) {
        return docsHref;
    }
};

/** Replaces link hrefs from google docs with the correct url */
export const replaceGoogleHrefs = (dom: JSDOM): void => {
    const linkElements = dom.window.document.querySelectorAll("a");
    linkElements.forEach((a) => a.href && (a.href = extractLinkUrl(a.href)));
};

/** Removes inline styles applied to elements in exported Google Docs
 * @param {JSDOM} dom JSDOM instance
 * @returns {void}
 */
export const removeDocumentStyles = (dom: JSDOM): void => {
    dom.window.document
        .querySelectorAll("*")
        .forEach((element) => element.removeAttribute("style"));
};

/** Removes any links or spans with no content */
export const removeEmptySpans = (dom: JSDOM): void => {
    dom.window.document
        .querySelectorAll("a, div, p, span")
        .forEach(
            (span) =>
                !span.textContent?.trim() &&
                !span.querySelector("img") &&
                span.remove(),
        );
};

/** Sets every image's referrerpolicy to 'no-referrer'
 *
 * Helps prevent 403 errors when loading images from Google
 *
 * @see https://stackoverflow.com/questions/56242788/http-403-on-images-loaded-from-googleusercontent-com
 */
export const removeImageReferrer = (dom: JSDOM) => {
    dom.window.document
        .querySelectorAll("img")
        .forEach((img) => img.setAttribute("referrerpolicy", "no-referrer"));
};

/** Extracts only the contents of the JSDOM's body tag */
export const extractDocumentHtml = (dom: JSDOM): string => {
    return dom.window.document.body.innerHTML;
};

/** Generates a snippet from the Google Doc */
export const extractSnippet = (dom: JSDOM, maxChars: number): string => {
    let snippet = "";
    // find the first paragraph with content
    let paragraph = findElementsWithMatcher(
        dom,
        "p",
        (p) => !!p.textContent?.trim(),
    )?.[0];
    // if no results, return empty string
    if (!paragraph) return snippet;
    // if the first paragraph didn't have enough text, go to the next element until it does have enough
    while (snippet.length < maxChars) {
        snippet += paragraph.textContent + "\n";
        const next = findNextSiblingWithContent(paragraph);
        if (!next) break;
        paragraph = next;
    }
    // if there's too many characters, use elipsis
    if (snippet.length > maxChars) snippet = snippet.slice(0, maxChars) + "...";
    // remove trailing/leading spaces
    return snippet.trim();
};

export const extractTitle = (dom: JSDOM): string => {
    const h = findElementsWithMatcher(
        dom,
        "h1, h2, h3, h4, h5, h6",
        (h) => !!h.textContent?.trim(),
    )?.[0];
    if (!h) return "";
    return h.textContent ?? "";
};
